# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_commentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='why',
            field=models.CharField(blank=True, choices=[('U', 'Upvote'), ('D', 'Downvote')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='why',
            field=models.CharField(blank=True, choices=[('U', 'Upvote'), ('D', 'Downvote')], max_length=8, null=True),
        ),
    ]
